importScripts(
  "background-native.js",
  "background.js",
  "background-custom-size.js",
  "background-provenance.js",
  "background-custom-storage-compat.js",
  "background-context-resolver.js",
  "background-context-menu.js",
  "background-sidepanel.js"
);
